# Generated by Django 3.1.5 on 2021-03-29 12:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
    ]
