# Generated by Django 3.1.5 on 2021-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210330_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, upload_to='Products/'),
        ),
    ]
