# Generated by Django 3.1.5 on 2021-03-30 11:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210330_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
    ]
